name: Backend CI

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"
          cache: gradle

      - name: Give execute permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Run checks, tests and coverage
        run: ./gradlew clean check

      - name: Build application
        run: ./gradlew bootJar